### ISSUE TITLE
always ZeroDivisionError

### ISSUE THREAD

**Issue by weiminye** [PacktPublishing/Hands-On-Artificial-Intelligence-for-Banking#1]
When run Chapter04/4A_WACC/4A_WACC_Optimization_for_Corp.py", always get ZeroDivisionError at line 262:

```
Chapter04/4A_WACC/4A_WACC_Optimization_for_Corp.py", line 262, in <module>
    g_NYSE = NYSE_val/prev_NYSE_val-1
ZeroDivisionError: division by zero
```

seems prev_NYSE_val is set to 0 at line 249

```
prev_NYSE_val = 0
```

then never change before line 262 so cause ZeroDivisionError

**Comment by jeffreynghm** [comment]
yes. looking into it.

**Comment by jeffreynghm** [comment]
Thanks for the comment, mind printing the i and NYSE_val, as well plz? as the codes is meant to be taking the NYSE_val in the first pass and skip the division u mentioned. 
i supposed u have the paid subscription to quandl?
    if i>0:
        g_NYSE = NYSE_val/prev_NYSE_val-1
        g_price = price_val/prev_price_val-1
        list_NYSE.append(g_NYSE)
        list_price.append(g_price)
    prev_NYSE_val = NYSE_val
    prev_price_val = price_val

**Comment by weiminye** [comment]
Thanks your reply. 

I do NOT have the paid subscription to quandl. 
I just have a free subscription to quandl. 

Yes, I think you are right. The prev_NYSE_val will get value when i = 0.
When I use the free subscription to quandl. It will throw an exception at 
```
NYSE_val = avg_p.values[0]
```
So NYSE_val will be always 0 then prev_NYSE_val also will be 0 too.

I think it is a big problem for Chinese readers.
I translated 2 tech books to the Chinese version before translating this book.
I think I fully understand how the Chinese readers think.
I do NOT think the Chinese readers will immediately have the paid subscription to quandl when reading your book.

My solution is :
1. I will add a translator footnote: it needs a  paid subscription to quandl, otherwise will get ZeroDivisionError.
2. I will buy a paid subscription to quandl, then run the program and make a recorded video and upload to online and let the Chinese reader can see the running result. 
The above operations are legal and never break the copyright of your book.
The above operations will be helpful for the book promotion and sales.
I also am the official and legal Chinese version translator of your book.
How do you think about my solution? Please feel free to let me know any concerns.

Thank you very much. Your book is a good book.

**Comment by jeffreynghm** [comment]
Hi Weimin
agree with both suggestions.
I have concern on copy right regarding 2. Is it something I can do to help?
Regards
Jeffrey

**Comment by ManikandanKurup-Packt** [comment]
Hi @weiminye @jeffreynghm 
Can we close this issue if the problem has been resolved?
